#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=01:30:00
#PBS -q serial
#PBS -P CBBI1243
#PBS -o stdout.txt
#PBS -e stderr.txt
#PBS -N SAIGE-kgp
#PBS -M eshkev001@myuct.ac.za
#PBS -m b

# module add chpc/BIOMODULES
# module load R/3.6.0-gcc7.2.0
# module load bcftools/1.6.33
# module load plink/1.90 

. ~/config.sh


#cd /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/saige/casecon

cd /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/kgp/saige

#~/projects/gwas/scripts/get_saige_pheno_covar.r saigegrm/high-quality-snps-for-grm.fam  saigegrm/pca.for.grm.cov
#~/projects/gwas/scripts/run_saige_grm.sh saigegrm/high-quality-snps-for-grm saigegrm/high-quality-snps-for-grm.pheno PHENO binary PC1,PC2,PC3,PC4,PC5,SEX,AGE FID saige.grm
~/projects/gwas/scripts/run_saige_single_variant_assoc.sh cm_kgp_casecontrol /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/saige/casecon/saige.grm.rda /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/saige/casecon/saige.grm.varianceRatio.txt saige.assoc
~/projects/gwas/scripts/format_saige_result_for_qqman.sh saige.assoc
~/projects/gwas/scripts/format_saige_result_for_annotation.sh saige.assoc
~/projects/gwas/scripts/make_annv_input.sh saige.assoc.gz
~/projects/gwas/scripts/assoc.r saige.assoc.txt.gz

 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/topmed/casecontrol/saige.grm.assoc.with.rare.var.topmed.txt
#   
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/kgp/casecontrol/saige.grm.assoc.with.rare.var.kgp.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh  /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/caapa/casecontrol/saige.grm.assoc.with.rare.var.caapa.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/sanger/casecontrol/saige.grm.assoc.with.rare.var.sanger.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/union/saige/saige.grm.assoc.union.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/complement/saige/casecon/saige.grm.assoc.complement.txt

