#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=01:30:00
#PBS -q serial
#PBS -P CBBI1243
#PBS -o stdout.txt
#PBS -e stderr.txt
#PBS -N eig
#PBS -M eshkev001@myuct.ac.za
#PBS -m b

module add chpc/BIOMODULES
module load R/4.1.0
module load EIGENSOFT/6.1.3 
# module load bcftools/1.6.33
# module load plink/1.90 

. ~/config.sh

cd /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/pca/cm/

~/projects/gwas/scripts/get_eig_params.sh cm_phased_ped
/home/kesoh/projects/gwas/scripts/run_convertf.sh 
/home/kesoh/projects/gwas/scripts/run_smartpca.sh cm_phased_ped 10 5 10 6.0 24
