#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=01:30:00
#PBS -q serial
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/stderr.txt
#PBS -N EIG
#PBS -M eshkev001@myuct.ac.za
#PBS -m b

. ~/config.sh

module add chpc/BIOMODULES
module load EIGENSOFT/6.1.3
# module load R/3.6.0-gcc7.2.0
# module load bcftools/1.6.33
# module load plink/1.90 

2018='/mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/28_OCT_2018/unimputed/pca/'
2019='/mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/28_OCT_2019/unimputed/pca/'
merge='/mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/pca/'
tanzania='/mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/tanzania/pca/'


for dir in $2018 $2019 $merge $tanzania; do
   cd $dir
   ~/projects/gwas/scripts/get_eig_params.sh eigen
   ~/projects/gwas/scripts/run_convertf.sh
   ~/projects/gwas/scripts/run_smartpca.sh eigen 10 5 10 6.0 24
done

