#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=01:30:00
#PBS -q serial
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/emmax/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/emmax/stderr.txt
#PBS -N EMMAX
#PBS -M eshkev001@myuct.ac.za
#PBS -m b

# module add chpc/BIOMODULES
# module load R/3.6.0-gcc7.2.0
# module load bcftools/1.6.33
# module load plink/1.90 

. ~/config.sh

emk=$(which emmax-kin-intel64)

base_dir="/mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/unimputed/"
script_dir="/home/kesoh/projects/gwas/scripts/"
cd ${base_dir}

cd ${base_dir}pca
plink2 --bfile ${base_dir}AW2018-2019.clean.pheno.updated.eigpruned --indep-pairwise 500000 50 0.2 --out prune

plink2 --bfile ${base_dir}AW2018-2019.clean.pheno.updated.eigpruned --pca 30 --extract prune.prune.in --out pca

/home/kesoh/projects/gwas/scripts/get_plink_covar.r pca.eigenvec
 
 
cd ${base_dir}emmax

plink \
    --bfile ${base_dir}AW2018-2019.clean.pheno.updated.eigpruned \
    --recode 12 transpose \
    --threads 24 \
    --keep-allele-order \
    --maf 0.01 \
    --geno 0.05 \
    --output-missing-genotype 0 \
    --hwe 1e-6 \
    --extract  ${base_dir}pca/prune.prune.in \
    --out emmax

$emk emmax -d 10 -v


/home/kesoh/projects/gwas/scripts/get_tfile.sh ${base_dir}AW2018-2019.clean.pheno.updated.eigpruned AW2018-2019.clean.pheno.updated.eigpruned
/home/kesoh/projects/gwas/scripts/get_emmax_covar.sh ${base_dir}pca/pca.cov AW2018-2019.clean.pheno.updated.eigpruned.tfam
/home/kesoh/projects/gwas/scripts/run_emmax.sh 2 AW2018-2019.clean.pheno.updated.eigpruned emmax.aBN.kinf

bgzip -f AW2018-2019.clean.pheno.updated.eigpruned.ps

/home/kesoh/projects/gwas/scripts/formart_emmax_output.r ${base_dir}AW2018-2019.clean.pheno.updated.eigpruned.bim AW2018-2019.clean.pheno.updated.eigpruned.ps.gz
/home/kesoh/projects/gwas/scripts/fdr.R AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz
/home/kesoh/projects/gwas/scripts/assoc.r AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz
/home/kesoh/projects/gwas/scripts/make_annv_input.sh AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz


# for dir in kgp topmed sanger caapa complement union; do
# 
# cd /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/${dir}/emmax
#   
# bgzip -f AW2018-2019.clean.pheno.updated.eigpruned.ps
#   
# ${script_dir}formart_emmax_output.r /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/${dir}/AW2018-2019.clean.pheno.updated.eigpruned.bim AW2018-2019.clean.pheno.updated.eigpruned.ps.gz
#   
# ${script_dir}fdr.R AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz
#   
# ${script_dir}assoc.r AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz
# 
# ${script_dir}make_annv_input.sh AW2018-2019.clean.pheno.updated.eigpruned.fmt.ps.gz
# 
# done
