#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:30:00
#PBS -q serial
#PBS -P CBBI1243
#PBS -o stdout.txt
#PBS -e stderr.txt
#PBS -N saige
#PBS -M eshkev001@myuct.ac.za
#PBS -m b

module add chpc/BIOMODULES
module load R/4.1.0
# module load bcftools/1.6.33
# module load plink/1.90 

. ~/config.sh

bed_prefix="cm_unimputed_dbp"
bed_dir="/mnt/lustre/groups/CBBI1243/KEVIN/arthemon/unimputed/dbp/"

cd /mnt/lustre/groups/CBBI1243/KEVIN/arthemon/unimputed/dbp/grm/

#~/projects/gwas/scripts/get_saige_pheno_covar.r high_quality_snps_for_nullglmm.fam pca.cov
#~/projects/gwas/scripts/run_saige_grm.sh high_quality_snps_for_nullglmm high_quality_snps_for_nullglmm.pheno PHENO quantitative PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,SEX,AGE SEX FID saige.grm false
~/projects/gwas/scripts/run_saige_single_variant_assoc.sh ${bed_dir}${bed_prefix} saige.grm.rda saige.grm.varianceRatio.txt saige.assoc
#~/projects/gwas/scripts/format_saige_result_for_qqman.sh saige.assoc
#~/projects/gwas/scripts/format_saige_result_for_annotation.sh saige.assoc
#~/projects/gwas/scripts/make_annv_input.sh saige.assoc.gz
#~/projects/gwas/scripts/assoc.r saige.assoc.txt.gz

 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/topmed/casecontrol/saige.grm.assoc.with.rare.var.topmed.txt
#   
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/kgp/casecontrol/saige.grm.assoc.with.rare.var.kgp.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh  /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/caapa/casecontrol/saige.grm.assoc.with.rare.var.caapa.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/sanger/casecontrol/saige.grm.assoc.with.rare.var.sanger.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/union/saige/saige.grm.assoc.union.txt
# 
# ~/projects/gwas/scripts/format_saige_result_for_annotation.sh /mnt/lustre/groups/CBBI1243/KEVIN/gwasdata/mergedBatches/imputed/complement/saige/casecon/saige.grm.assoc.complement.txt

